version: "3.6"

services:
  web:
    image: uclalibrary/californica:latest
    depends_on:
      - db
      - fedora
      - redis
      - solr
    env_file:
      - ./.env.sample
    environment:
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/californica
      - ./data:/opt/data
      - bundle_dir:/usr/local/bundle
      - log:/californica/log
      - tmp:/californica/tmp
    working_dir: /californica

  fedora:
    image: nulib/fcrepo4:4.7.5
    ports:
      - "8984:8080"
    volumes:
      - fcrepo_data:/data

  fedora_test:
    image: nulib/fcrepo4:4.7.5
    ports:
      - "8986:8080"

  db:
    image: mysql:5.6
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_USER: californica
      # MYSQL_PASSWORD: californica

  redis:
    image: redis:4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  solr:
    build:
      context: .
      dockerfile: docker/Dockerfile.solr
    volumes:
      - solr_data:/opt/solr/server/solr/mycores/californica/data
    ports:
      - "8983:8983"

  solr_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.solr
    ports:
      - "8985:8983"

volumes:
  bundle_dir:
  fcrepo_data:
  log:
  mysql_data:
  redis_data:
  solr_data:
  tmp:
