FROM solr

RUN mkdir /opt/solr/server/solr/mycores/hyrax
RUN mkdir /opt/solr/server/solr/mycores/hyrax/data
RUN touch /opt/solr/server/solr/mycores/hyrax/core.properties
COPY --chown=solr:solr /solr/config /opt/solr/server/solr/mycores/hyrax/conf
