# This is a sample config file that points to a solr server for each environment
development:
  url: http://solr:8983/solr/californica
test:
  url: http://solr_test:8983/solr/californica
production:
url: http://your.production.server:8080/bl_solr/core0
